### ISSUE TITLE
Issues with ./inference_demo.ipynb

### ISSUE THREAD

**Issue by BadourAlBahar** [googleinterns/humangps#4]
Hi, 

Congratulations on the great work!

I am trying to run the inference_demo.ipynb you provided, however, I am unable to get the correct results. The flow and features look different than your reported results.

I noticed that you ran this:
`path = 'humangps_pretrained'`
`model = tf.saved_model.load(path)`

Would you please share the humangps_pretrained model. 

Thanks!

**Comment by feitongt** [comment]
Hi,

Thanks for your interest! We provide a script in this repository to download pretrained model, we can run "bash download_model.sh" to download it.

Best,

**Comment by BadourAlBahar** [comment]
Thanks. 

I have followed the instructions for downloading the pretrained models and following the code in here to reload it.

`# load pretrained model.`
`checkpoint_path = './checkpoint/pretrained_model'`

`model_hparams = {`
`      'loss_hparams': {`
 `         'correspondence_loss_weight': 0.3,`
  `        'triplet_loss_weight': 2.0,`
   `       'dense_geodesic_loss_weight': 6.0,`
`          'cross_dense_geodesic_loss_weight': 4.0,`
`          'sparse_ordinal_geodesic_loss_weight': 2.0,`
`      },`
`      'flow_scale_factor': 20.0,`
`      'return_feature_pyramid': False,`
`      'feature_extractor': 'resunet',`
`#       'eval_search_size': (384, 256),`
`      'filters_sequence': (16, 32, 64, 96, 128, 128, 196),`
`  }`

`model = geodesic_feature_network.GeoFeatureNet(model_hparams)`

`checkpoint = tf.train.Checkpoint(`
`      model=model,`
`      step=tf.Variable(-1, dtype=tf.int64),`
`      training_finished=tf.Variable(False, dtype=tf.bool),`
`  )`

`status = checkpoint.restore(checkpoint_path)`
`status.assert_existing_objects_matched()`
`status.expect_partial()`

However, the results I get are incorrect. I thought based on the last lines of code:
`path = 'humangps_pretrained'`
`model = tf.saved_model.load(path)`

Maybe you can load the correct model. But the `'humangps_pretrained'` is not shared.

Please advise.

**Comment by feitongt** [comment]
Hi,

Sorry for the confusion. There is a bug in the demo code and I just removed the rebundant code in the demo code. The bug should be fixed. 

The model should be loaded with 

`checkpoint = tf.train.Checkpoint(`
`      model=model,`
`      step=tf.Variable(-1, dtype=tf.int64),`
`      training_finished=tf.Variable(False, dtype=tf.bool),`
`  )`

`status = checkpoint.restore(checkpoint_path)`
`status.assert_existing_objects_matched()`
`status.expect_partial()`

instead of

`path = 'humangps_pretrained'`
`model = tf.saved_model.load(path)`

Thanks for reporting the issue!
